[package]
name = "key-synth"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
egui = "0.33.2"
egui_extras = { version = "0.33.2", features = ["all_loaders"] }
image = { version = "0.25", features = ["png"] }
midir = "0.10.3"
